repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pytest-style

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
      - id: mypy
        # Avoid error: Duplicate module named 'setup'
        # https://github.com/python/mypy/issues/4008
        exclude: ^tests/test_data/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [--ini, .bandit]
        exclude: ^tests/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier

  - repo: https://github.com/jazzband/pip-tools
    rev: 5.5.0
    hooks:
      - name: Build requirements.txt
        id: pip-compile
        files: ^((requirements(-.*)?\.(in|txt))|setup.py)$
      - name: Build requirements-dev.txt
        id: pip-compile
        files: ^((requirements(-.*)?\.(in|txt))|setup.py)$
        args: ["--allow-unsafe", "requirements-dev.in"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
